name: day2
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  basics: ^0.10.0
  buffer: ^1.2.3
  build_runner: ^2.4.10
  built_collection: ^5.1.1
  built_value: ^8.9.2
  cron: ^0.6.0
  drift: ^2.18.0
  drift_postgres: ^1.2.3
  elastic_client: ^0.3.15
  executor: ^2.2.3
  ffi: ^2.1.2
  ffigen: ^12.0.0
  graphql: ^5.2.0-beta.7
  grpc: ^3.2.4
  http: ^1.2.1
  http2: ^2.3.0
  http_client: ^1.5.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  macros: ^0.0.1
  match: ^0.4.1
  matcher: ^0.12.16+1
  os_detect: ^2.0.1
  oxidized: ^6.1.0
  #result_dart: ^1.1.1
  #result_monad: ^2.3.2
  # result_type: ^1.0.0
  #path_provider: ^2.1.3
  pool: ^1.5.1
  postgres: ^3.2.1
  postgrest: ^2.1.2
  sqlite3: ^2.4.3
  #sqlite3_flutter_libs: ^0.5.22
  test: ^1.25.5
  toml: ^0.15.0
  # data_class_plugin: any
  # http_client_plugin: any
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  #tachyon: any
  # test: ^1.25.5
